version: '3'
services:
 app:
  container_name: chaos-demo-task-app
  restart: always
  build: .
  ports:
   - '80:9000'
  links:
   - mongo

 mongo:
  container_name: mongo
  image: mongo
  ports:
   - '27017:27017'
